arctos:
  #Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  #JointPosition Controllers via PID
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 700, i: 50, d: 70}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 700, i: 50, d: 70}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 2400, i: 0, d: 5}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 6000, i: 0, d: 5}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 50, i: 1, d: 1}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 50, i: 1, d: 1}

  jaw1_position_controller:
    type: effort_controllers/JointPositionController
    joint: jaw1
    pid: {p: 100, i: 2, d: 5}

  jaw2_position_controller:
    type: effort_controllers/JointPositionController
    joint: jaw2
    pid: {p: 100, i: 2, d: 5}