arctos:
  arm_controller:
    # This type means that software inputs JointTrajectoryController, and outputs position controller
    type: position_controllers/JointTrajectoryController #JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint1: {trajectory: 0.5, goal: 0.5}
      joint2: {trajectory: 0.5, goal: 0.5}
      joint3: {trajectory: 0.5, goal: 0.5}
      joint4: {trajectory: 0.5, goal: 0.5}
      joint5: {trajectory: 0.5, goal: 0.5}
      joint6: {trajectory: 0.5, goal: 0.5}
    stop_trajectory_duration: 0.6
    state_publish_rate: 25
    action_monitor_rate: 10

  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - jaw1
      - jaw2
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      jaw1: {trajectory: 0.5, goal: 0.5}
      jaw2: {trajectory: 0.5, goal: 0.5}
    stop_trajectory_duration: 0.6
    state_publish_rate: 25
    action_monitor_rate: 10