# arm_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - joint1
#     - joint2
#     - joint3
#     - joint4
#     - joint5
#     - joint6
#   gains:
#     joint1:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint2:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint3:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint4:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint5:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint6:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
# gripper_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - jaw1
#   gains:
#     jaw1:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: /arctos/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6

  - name: /arctos/gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - jaw1